development:
  secret_key_base: '78375cae3aa8e30cb8fce028f8faffb93d5d73214b16248b7f222f7fc37203ee0c7799193e7f79b61614b3a467eb41a213b0cc6a869a3d6acf8dfb753eb9ad2e'

test:
  secret_key_base: '78375cae3aa8e30cb8fce028f8faffb93d5d73214b16248b7f222f7fc37203ee0c7799193e7f79b61614b3a467eb41a213b0cc6a869a3d6acf8dfb753eb9ad2e'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
